trading:
    capital: 100000000 # 100M IDR
    risk_per_trade: 0.02 # 2%
    tickers:
        - BBCA.JK
        - TLKM.JK
        - ASII.JK
        - BMRI.JK
        - GOTO.JK

telegram:
    enabled: true # Set to true to enable bot
    bot_token: "8274271189:AAEwi4xE80n9mDmPguCDEtX91GQzh09NiPc"
    chat_id: "603041435"
