import json

f = 'notebooks/00b_model_retraining_cnn.ipynb'
with open(f, 'r', encoding='utf-8') as file:
    data = json.load(file)

section3 = [
    "# \U0001f9e0 SECTION 3: CORE LOGIC (CNN-LSTM Meta-Labeling Pipeline)\n",
    "import optuna, warnings, ta\n",
    "optuna.logging.set_verbosity(optuna.logging.WARNING)\n",
    "warnings.filterwarnings('ignore', category=FutureWarning)\n",
    "\n",
    "def build_cnn_panel_data(universe, seq_len=30, period='5y'):\n",
    "    all_X, all_y = [], []\n",
    "    n_total = len(universe)\n",
    "    print(f'\\U0001f4c9 Fetching {period} of data for {n_total} tickers...')\n",
    "    skip_empty = 0\n",
    "    skip_short = 0\n",
    "    fail_err = 0\n",
    "    ok_count = 0\n",
    "    for idx, ticker in enumerate(universe):\n",
    "        if idx % 50 == 0:\n",
    "            print(f'  ... processing {idx}/{n_total} ...')\n",
    "        try:\n",
    "            df = yf.download(ticker, period=period, progress=False, auto_adjust=True)\n",
    "            if df is None or len(df) == 0:\n",
    "                skip_empty += 1\n",
    "                continue\n",
    "            if len(df) < seq_len + 10:\n",
    "                skip_short += 1\n",
    "                continue\n",
    "            close = df['Close'].squeeze()\n",
    "            high = df['High'].squeeze()\n",
    "            low = df['Low'].squeeze()\n",
    "            volume = df['Volume'].squeeze()\n",
    "            if hasattr(close, 'ndim') and close.ndim > 1:\n",
    "                close = close.iloc[:, 0]\n",
    "            if hasattr(high, 'ndim') and high.ndim > 1:\n",
    "                high = high.iloc[:, 0]\n",
    "            if hasattr(low, 'ndim') and low.ndim > 1:\n",
    "                low = low.iloc[:, 0]\n",
    "            if hasattr(volume, 'ndim') and volume.ndim > 1:\n",
    "                volume = volume.iloc[:, 0]\n",
    "            atr = ta.volatility.AverageTrueRange(high=high, low=low, close=close, window=14).average_true_range()\n",
    "            raw = np.column_stack([df['Open'].squeeze().values, high.values, low.values, close.values, volume.values, atr.values])\n",
    "            valid_start = np.argmax(~np.isnan(raw).any(axis=1))\n",
    "            raw = raw[valid_start:]\n",
    "            close_vals = close.values[valid_start:]\n",
    "            ticker_x, ticker_y = [], []\n",
    "            for i in range(len(raw) - seq_len - 1):\n",
    "                seq = raw[i:i+seq_len]\n",
    "                seq_min = seq.min(axis=0)\n",
    "                seq_max = seq.max(axis=0)\n",
    "                norm_seq = (seq - seq_min) / (seq_max - seq_min + 1e-7)\n",
    "                ticker_x.append(norm_seq)\n",
    "                y_val = 1 if close_vals[i+seq_len+1] > close_vals[i+seq_len] else 0\n",
    "                ticker_y.append(y_val)\n",
    "            if len(ticker_x) > 0:\n",
    "                all_X.extend(ticker_x)\n",
    "                all_y.extend(ticker_y)\n",
    "                ok_count += 1\n",
    "        except Exception as e:\n",
    "            fail_err += 1\n",
    "            if fail_err <= 5:\n",
    "                print(f'\\u26a0\\ufe0f {ticker}: {type(e).__name__}: {e}')\n",
    "            continue\n",
    "    print(f'\\U0001f4ca Pipeline: OK={ok_count} | Empty={skip_empty} | Short={skip_short} | Error={fail_err}')\n",
    "    if len(all_X) == 0:\n",
    "        print(f'\\u274c No valid data from {n_total} tickers!')\n",
    "        return None, None\n",
    "    print(f'\\u2705 Aggregated {ok_count}/{n_total} tickers | {len(all_y)} sequences.')\n",
    "    return np.array(all_X), np.array(all_y)\n",
    "\n",
    "def build_meta_labels(y_true, rf_meta_path='/kaggle/working/rf_oos_meta.json'):\n",
    "    try:\n",
    "        import json as _json\n",
    "        with open(rf_meta_path) as mf:\n",
    "            meta = _json.load(mf)\n",
    "        print(f'\\u2705 Loaded RF meta-labels: {len(meta[\"oos_correct\"])} OOS predictions (RF Val Acc: {meta[\"val_acc\"]:.2%})')\n",
    "        return np.array(meta['oos_correct']), True\n",
    "    except FileNotFoundError:\n",
    "        print('\\u26a0\\ufe0f RF meta-labels not found. Training in standalone mode.')\n",
    "        return y_true, False\n",
    "\n",
    "def train_cnn(X, y, conv1=64, conv2=128, lstm_units=64, dropout=0.4, lr=1e-3, epochs=40, batch_size=128):\n",
    "    print(f'\\U0001f9e0 Training Deep L-CNN Meta Brain on {len(y)} sequences...')\n",
    "    n_features = X.shape[2]\n",
    "    seq_len = X.shape[1]\n",
    "    model = tf.keras.Sequential([\n",
    "        tf.keras.layers.Conv1D(conv1, 3, activation='relu', padding='same', input_shape=(seq_len, n_features)),\n",
    "        tf.keras.layers.BatchNormalization(),\n",
    "        tf.keras.layers.MaxPooling1D(2),\n",
    "        tf.keras.layers.Conv1D(conv2, 3, activation='relu', padding='same'),\n",
    "        tf.keras.layers.BatchNormalization(),\n",
    "        tf.keras.layers.LSTM(lstm_units, return_sequences=False),\n",
    "        tf.keras.layers.Dense(64, activation='relu'),\n",
    "        tf.keras.layers.Dropout(dropout),\n",
    "        tf.keras.layers.Dense(2, activation='softmax')\n",
    "    ])\n",
    "    lr_schedule = tf.keras.optimizers.schedules.ExponentialDecay(initial_learning_rate=lr, decay_steps=10000, decay_rate=0.9)\n",
    "    optimizer = tf.keras.optimizers.Adam(learning_rate=lr_schedule)\n",
    "    model.compile(optimizer=optimizer, loss='sparse_categorical_crossentropy', metrics=['accuracy'])\n",
    "    split_idx = int(len(X) * 0.85)\n",
    "    X_tr, X_te = X[:split_idx], X[split_idx:]\n",
    "    y_tr, y_te = y[:split_idx], y[split_idx:]\n",
    "    early_stop = tf.keras.callbacks.EarlyStopping(monitor='val_accuracy', patience=5, restore_best_weights=True)\n",
    "    history = model.fit(X_tr, y_tr, epochs=epochs, batch_size=batch_size, validation_data=(X_te, y_te), callbacks=[early_stop], verbose=1)\n",
    "    t_acc = max(history.history['accuracy'])\n",
    "    v_acc = max(history.history['val_accuracy'])\n",
    "    return model, t_acc, v_acc\n",
    "\n",
    "def optimize_cnn(X, y, n_trials=20):\n",
    "    print(f'\\U0001f50d Running Optuna HPO for CNN ({n_trials} trials)...')\n",
    "    def objective(trial):\n",
    "        params = {\n",
    "            'conv1': trial.suggest_categorical('conv1', [32, 64, 128]),\n",
    "            'conv2': trial.suggest_categorical('conv2', [64, 128, 256]),\n",
    "            'lstm_units': trial.suggest_categorical('lstm_units', [32, 64, 128]),\n",
    "            'dropout': trial.suggest_float('dropout', 0.2, 0.5),\n",
    "            'lr': trial.suggest_float('lr', 1e-4, 1e-2, log=True),\n",
    "            'batch_size': trial.suggest_categorical('batch_size', [64, 128, 256]),\n",
    "        }\n",
    "        _, _, v_acc = train_cnn(X, y, epochs=10, **params)\n",
    "        return v_acc\n",
    "    study = optuna.create_study(direction='maximize')\n",
    "    study.optimize(objective, n_trials=n_trials, timeout=1500)\n",
    "    print(f'\\u2705 Optuna Best Val Acc: {study.best_value:.4f}')\n",
    "    print(f'\\u2705 Best Params: {study.best_params}')\n",
    "    return study.best_params, study.best_value\n",
]

for cell in data['cells']:
    if cell['cell_type'] == 'code':
        src = "".join(cell['source'])
        if "def build_cnn_panel_data" in src:
            cell['source'] = section3
            break

with open(f, 'w', encoding='utf-8') as file:
    json.dump(data, file, indent=1)
print("00B FIXED: warnings suppressed + pipeline diagnostics added!")
