import json

f = 'notebooks/00a_model_retraining_rf.ipynb'
with open(f, 'r', encoding='utf-8') as file:
    data = json.load(file)

# ════════════════════════════════════════════════════════
# SECTION 3: CORE LOGIC — Complete Rewrite
# ════════════════════════════════════════════════════════
section3 = [
    "# \U0001f9e0 SECTION 3: CORE LOGIC (Institutional Alpha Pipeline)\n",
    "from sklearn.ensemble import RandomForestClassifier\n",
    "from sklearn.model_selection import train_test_split\n",
    "import numpy as np\n",
    "import ta\n",
    "import optuna\n",
    "optuna.logging.set_verbosity(optuna.logging.WARNING)\n",
    "\n",
    "# ── Fractional Differentiation (Stationary with Long Memory) ──\n",
    "def frac_diff(series, d=0.4, thres=1e-5):\n",
    "    weights = [1.0]\n",
    "    for k in range(1, len(series)):\n",
    "        w = -weights[-1] * (d - k + 1) / k\n",
    "        if abs(w) < thres:\n",
    "            break\n",
    "        weights.append(w)\n",
    "    weights = np.array(weights[::-1])\n",
    "    result = np.full(len(series), np.nan)\n",
    "    for t in range(len(weights) - 1, len(series)):\n",
    "        result[t] = np.dot(weights, series[t - len(weights) + 1:t + 1])\n",
    "    return result\n",
    "\n",
    "# ── Triple Barrier Labeling (Risk-Aware Target) ──\n",
    "def triple_barrier_label(close_arr, t_horizon=5, sl_pct=0.02, tp_pct=0.03):\n",
    "    labels = np.zeros(len(close_arr))\n",
    "    for i in range(len(close_arr) - t_horizon):\n",
    "        future = close_arr[i+1:i+1+t_horizon]\n",
    "        entry = close_arr[i]\n",
    "        if entry == 0:\n",
    "            continue\n",
    "        tp_hit = np.any(future >= entry * (1 + tp_pct))\n",
    "        sl_hit = np.any(future <= entry * (1 - sl_pct))\n",
    "        tp_idx = np.argmax(future >= entry * (1 + tp_pct)) if tp_hit else t_horizon\n",
    "        sl_idx = np.argmax(future <= entry * (1 - sl_pct)) if sl_hit else t_horizon\n",
    "        if tp_hit and (tp_idx <= sl_idx):\n",
    "            labels[i] = 1\n",
    "        elif sl_hit:\n",
    "            labels[i] = -1\n",
    "    return labels\n",
    "\n",
    "# ── Walk-Forward Expanding Window CV ──\n",
    "def walk_forward_cv(model_cls, model_params, X, y, n_splits=4):\n",
    "    chunk = len(X) // (n_splits + 1)\n",
    "    scores = []\n",
    "    for i in range(n_splits):\n",
    "        train_end = chunk * (i + 2)\n",
    "        test_end = min(train_end + chunk, len(X))\n",
    "        if test_end <= train_end:\n",
    "            continue\n",
    "        m = model_cls(**model_params, n_jobs=-1, random_state=42)\n",
    "        m.fit(X[:train_end], y[:train_end])\n",
    "        scores.append(m.score(X[train_end:test_end], y[train_end:test_end]))\n",
    "    return scores\n",
    "\n",
    "# ── 12-Feature Builder ──\n",
    "def build_panel_data(universe, period='5y'):\n",
    "    all_X, all_y = [], []\n",
    "    feature_names = ['Returns','RSI','MACD','BB_High','BB_Low','ATR','ADX','OBV_norm','day_of_week','week_of_month','frac_diff_close','vol_ratio']\n",
    "    print(f'\U0001f4c9 Fetching {period} of data for {len(universe)} tickers...')\n",
    "    for ticker in universe:\n",
    "        try:\n",
    "            df = yf.download(ticker, period=period, progress=False)\n",
    "            if len(df) < 100:\n",
    "                continue\n",
    "            close = df['Close'].squeeze()\n",
    "            high = df['High'].squeeze()\n",
    "            low = df['Low'].squeeze()\n",
    "            volume = df['Volume'].squeeze()\n",
    "            df['Returns'] = close.pct_change()\n",
    "            df['RSI'] = ta.momentum.RSIIndicator(close=close, window=14).rsi()\n",
    "            macd = ta.trend.MACD(close=close)\n",
    "            df['MACD'] = macd.macd_diff()\n",
    "            boll = ta.volatility.BollingerBands(close=close, window=20, window_dev=2)\n",
    "            df['BB_High'] = boll.bollinger_hband_indicator()\n",
    "            df['BB_Low'] = boll.bollinger_lband_indicator()\n",
    "            df['ATR'] = ta.volatility.AverageTrueRange(high=high, low=low, close=close, window=14).average_true_range()\n",
    "            df['ADX'] = ta.trend.ADXIndicator(high=high, low=low, close=close, window=14).adx()\n",
    "            obv = ta.volume.OnBalanceVolumeIndicator(close=close, volume=volume).on_balance_volume()\n",
    "            df['OBV_norm'] = (obv - obv.rolling(20).mean()) / (obv.rolling(20).std() + 1e-7)\n",
    "            df['day_of_week'] = df.index.dayofweek\n",
    "            df['week_of_month'] = (df.index.day - 1) // 7\n",
    "            fd = frac_diff(close.values, d=0.4)\n",
    "            df['frac_diff_close'] = fd\n",
    "            vol_ma = volume.rolling(20).mean()\n",
    "            df['vol_ratio'] = volume / (vol_ma + 1e-7)\n",
    "            df = df.dropna()\n",
    "            if len(df) < 50:\n",
    "                continue\n",
    "            close_arr = close.reindex(df.index).values.flatten()\n",
    "            y = triple_barrier_label(close_arr, t_horizon=5, sl_pct=0.02, tp_pct=0.03)\n",
    "            valid = len(df) if len(df) <= len(y) else len(y)\n",
    "            X = df[feature_names].values[:valid]\n",
    "            y = y[:valid]\n",
    "            mask = ~np.isnan(X).any(axis=1)\n",
    "            all_X.append(X[mask])\n",
    "            all_y.append(y[mask])\n",
    "        except Exception:\n",
    "            continue\n",
    "    print('\u2705 Successfully aggregated market data.')\n",
    "    if len(all_X) == 0:\n",
    "        return None, None, feature_names\n",
    "    return np.vstack(all_X), np.concatenate(all_y), feature_names\n",
    "\n",
    "# ── Optuna HPO ──\n",
    "def optimize_rf(X, y, n_trials=50):\n",
    "    print(f'\U0001f50d Running Optuna HPO ({n_trials} trials)...')\n",
    "    def objective(trial):\n",
    "        params = {\n",
    "            'n_estimators': trial.suggest_int('n_estimators', 100, 500),\n",
    "            'max_depth': trial.suggest_int('max_depth', 5, 20),\n",
    "            'min_samples_leaf': trial.suggest_int('min_samples_leaf', 3, 20),\n",
    "            'max_features': trial.suggest_categorical('max_features', ['sqrt', 'log2']),\n",
    "        }\n",
    "        scores = walk_forward_cv(RandomForestClassifier, params, X, y, n_splits=4)\n",
    "        return np.mean(scores) if scores else 0.0\n",
    "    study = optuna.create_study(direction='maximize')\n",
    "    study.optimize(objective, n_trials=n_trials, timeout=600)\n",
    "    print(f'\u2705 Optuna Best Val Acc: {study.best_value:.4f}')\n",
    "    print(f'\u2705 Best Params: {study.best_params}')\n",
    "    return study.best_params, study.best_value\n",
]

# ════════════════════════════════════════════════════════
# SECTION 4: MAIN EXECUTION — Complete Rewrite
# ════════════════════════════════════════════════════════
section4 = [
    "# \U0001f680 SECTION 4: MAIN EXECUTION\n",
    "def run_retrain():\n",
    "    secrets = KaggleInfra.load_secrets()\n",
    "    fb = FirebaseHandler(secrets)\n",
    "    output_dir = '/kaggle/working/'\n",
    "    \n",
    "    universe = get_full_idx_universe()\n",
    "    \n",
    "    # 1. Build 12-Feature Panel with Triple Barrier Labels\n",
    "    X, y, feature_names = build_panel_data(universe)\n",
    "    if X is None:\n",
    "        print('\u26a0\ufe0f Retraining aborted due to data fetch failure.')\n",
    "        return\n",
    "    \n",
    "    print(f'\U0001f4ca Label Distribution: +1={np.sum(y==1)}, 0={np.sum(y==0)}, -1={np.sum(y==-1)}')\n",
    "    \n",
    "    # 2. Optuna Hyperparameter Search with Walk-Forward CV\n",
    "    best_params, best_cv_score = optimize_rf(X, y, n_trials=50)\n",
    "    \n",
    "    # 3. Final Training with Best Params (Walk-Forward OOS)\n",
    "    split_idx = int(len(X) * 0.85)\n",
    "    X_train, X_test = X[:split_idx], X[split_idx:]\n",
    "    y_train, y_test = y[:split_idx], y[split_idx:]\n",
    "    \n",
    "    rf_model = RandomForestClassifier(**best_params, n_jobs=-1, random_state=42)\n",
    "    rf_model.fit(X_train, y_train)\n",
    "    train_acc = rf_model.score(X_train, y_train)\n",
    "    val_acc = rf_model.score(X_test, y_test)\n",
    "    \n",
    "    # 4. Export OOS Predictions for Meta-Labeling (CNN needs this)\n",
    "    oos_preds = rf_model.predict(X_test)\n",
    "    oos_correct = (oos_preds == y_test).astype(int).tolist()\n",
    "    import json as _json\n",
    "    with open(os.path.join(output_dir, 'rf_oos_meta.json'), 'w') as mf:\n",
    "        _json.dump({'oos_correct': oos_correct, 'oos_preds': oos_preds.tolist(), 'val_acc': val_acc}, mf)\n",
    "    \n",
    "    # 5. Save Model Artifact\n",
    "    brain_data = {\n",
    "        'model': rf_model,\n",
    "        'features': feature_names,\n",
    "        'best_params': best_params,\n",
    "        'train_accuracy': train_acc,\n",
    "        'val_accuracy': val_acc,\n",
    "        'optuna_cv_score': best_cv_score,\n",
    "        'trained_at': datetime.now().isoformat()\n",
    "    }\n",
    "    joblib.dump(brain_data, os.path.join(output_dir, 'glu_brain_v1.joblib'))\n",
    "    \n",
    "    # 6. Rich Firebase Telemetry\n",
    "    log_lines = [\n",
    "        'RF Institutional Training Complete.',\n",
    "        f'\U0001f393 Training Acc: {train_acc:.2%}',\n",
    "        f'\U0001f6e1\ufe0f OOS Validation Acc: {val_acc:.2%}',\n",
    "        f'\U0001f50d Optuna Best CV: {best_cv_score:.2%}',\n",
    "        f'\U0001f4ca Universe: {len(universe)} symbols | Samples: {len(y)}',\n",
    "        f'\U0001f3af Label Dist: +1={int(np.sum(y==1))}, 0={int(np.sum(y==0))}, -1={int(np.sum(y==-1))}',\n",
    "        f'\U0001f9e0 Features: {len(feature_names)} | Params: {best_params}',\n",
    "    ]\n",
    "    fb.log_event('RETRAINING_RF', chr(10).join(log_lines))\n",
    "    for line in log_lines:\n",
    "        print(line)\n",
    "\n",
    "run_retrain()\n",
]

# ── Also update pip install cell ──
for cell in data['cells']:
    if cell['cell_type'] == 'code':
        src = "".join(cell['source'])
        if '!pip install' in src:
            if 'optuna' not in src:
                new_src = src.rstrip()
                if 'ta' not in new_src:
                    new_src += ' ta'
                new_src += ' optuna'
                cell['source'] = [new_src]

# ── Inject into correct cells ──
for cell in data['cells']:
    if cell['cell_type'] == 'code':
        src = "".join(cell['source'])
        if "def build_panel_data" in src:
            cell['source'] = section3
        elif "def run_retrain" in src:
            cell['source'] = section4

with open(f, 'w', encoding='utf-8') as file:
    json.dump(data, file, indent=1)
print("00A FULLY PATCHED WITH PHASE 18 QUANT ALPHA!")
