import json

f = 'notebooks/00a_model_retraining_rf.ipynb'
with open(f, 'r', encoding='utf-8') as file:
    data = json.load(file)

section3 = [
    "# \U0001f9e0 SECTION 3: CORE LOGIC (Institutional Alpha Pipeline)\n",
    "from sklearn.ensemble import RandomForestClassifier\n",
    "from sklearn.model_selection import train_test_split\n",
    "import numpy as np\n",
    "import ta\n",
    "import optuna\n",
    "optuna.logging.set_verbosity(optuna.logging.WARNING)\n",
    "\n",
    "def frac_diff(series, d=0.4, thres=1e-5):\n",
    "    weights = [1.0]\n",
    "    for k in range(1, len(series)):\n",
    "        w = -weights[-1] * (d - k + 1) / k\n",
    "        if abs(w) < thres:\n",
    "            break\n",
    "        weights.append(w)\n",
    "    weights = np.array(weights[::-1])\n",
    "    result = np.full(len(series), np.nan)\n",
    "    for t in range(len(weights) - 1, len(series)):\n",
    "        result[t] = np.dot(weights, series[t - len(weights) + 1:t + 1])\n",
    "    return result\n",
    "\n",
    "def triple_barrier_label(close_arr, t_horizon=5, sl_pct=0.02, tp_pct=0.03):\n",
    "    labels = np.zeros(len(close_arr))\n",
    "    for i in range(len(close_arr) - t_horizon):\n",
    "        future = close_arr[i+1:i+1+t_horizon]\n",
    "        entry = close_arr[i]\n",
    "        if entry == 0:\n",
    "            continue\n",
    "        tp_hit = np.any(future >= entry * (1 + tp_pct))\n",
    "        sl_hit = np.any(future <= entry * (1 - sl_pct))\n",
    "        tp_idx = np.argmax(future >= entry * (1 + tp_pct)) if tp_hit else t_horizon\n",
    "        sl_idx = np.argmax(future <= entry * (1 - sl_pct)) if sl_hit else t_horizon\n",
    "        if tp_hit and (tp_idx <= sl_idx):\n",
    "            labels[i] = 1\n",
    "        elif sl_hit:\n",
    "            labels[i] = -1\n",
    "    return labels\n",
    "\n",
    "def walk_forward_cv(model_cls, model_params, X, y, n_splits=4):\n",
    "    chunk = len(X) // (n_splits + 1)\n",
    "    scores = []\n",
    "    for i in range(n_splits):\n",
    "        train_end = chunk * (i + 2)\n",
    "        test_end = min(train_end + chunk, len(X))\n",
    "        if test_end <= train_end:\n",
    "            continue\n",
    "        m = model_cls(**model_params, n_jobs=-1, random_state=42)\n",
    "        m.fit(X[:train_end], y[:train_end])\n",
    "        scores.append(m.score(X[train_end:test_end], y[train_end:test_end]))\n",
    "    return scores\n",
    "\n",
    "def build_panel_data(universe, period='5y'):\n",
    "    all_X, all_y = [], []\n",
    "    feature_names = ['Returns','RSI','MACD','BB_High','BB_Low','ATR','ADX','OBV_norm','day_of_week','week_of_month','frac_diff_close','vol_ratio']\n",
    "    print(f'\U0001f4c9 Fetching {period} of data for {len(universe)} tickers...')\n",
    "    fail_count = 0\n",
    "    for ticker in universe:\n",
    "        try:\n",
    "            df = yf.download(ticker, period=period, progress=False)\n",
    "            if len(df) < 100:\n",
    "                continue\n",
    "            close = df['Close'].squeeze()\n",
    "            high = df['High'].squeeze()\n",
    "            low = df['Low'].squeeze()\n",
    "            volume = df['Volume'].squeeze()\n",
    "            df['Returns'] = close.pct_change()\n",
    "            df['RSI'] = ta.momentum.RSIIndicator(close=close, window=14).rsi()\n",
    "            macd_ind = ta.trend.MACD(close=close)\n",
    "            df['MACD'] = macd_ind.macd_diff()\n",
    "            boll = ta.volatility.BollingerBands(close=close, window=20, window_dev=2)\n",
    "            df['BB_High'] = boll.bollinger_hband_indicator()\n",
    "            df['BB_Low'] = boll.bollinger_lband_indicator()\n",
    "            df['ATR'] = ta.volatility.AverageTrueRange(high=high, low=low, close=close, window=14).average_true_range()\n",
    "            df['ADX'] = ta.trend.ADXIndicator(high=high, low=low, close=close, window=14).adx()\n",
    "            obv = ta.volume.OnBalanceVolumeIndicator(close=close, volume=volume).on_balance_volume()\n",
    "            df['OBV_norm'] = (obv - obv.rolling(20).mean()) / (obv.rolling(20).std() + 1e-7)\n",
    "            df['day_of_week'] = df.index.dayofweek\n",
    "            df['week_of_month'] = (df.index.day - 1) // 7\n",
    "            fd = frac_diff(close.values.flatten(), d=0.4)\n",
    "            df['frac_diff_close'] = fd\n",
    "            vol_ma = volume.rolling(20).mean()\n",
    "            df['vol_ratio'] = volume / (vol_ma + 1e-7)\n",
    "            df = df.dropna()\n",
    "            if len(df) < 50:\n",
    "                continue\n",
    "            close_arr = close.reindex(df.index).values.flatten()\n",
    "            y = triple_barrier_label(close_arr, t_horizon=5, sl_pct=0.02, tp_pct=0.03)\n",
    "            valid = min(len(df), len(y))\n",
    "            X = df[feature_names].values[:valid]\n",
    "            y = y[:valid]\n",
    "            mask = ~np.isnan(X).any(axis=1)\n",
    "            if mask.sum() > 0:\n",
    "                all_X.append(X[mask])\n",
    "                all_y.append(y[mask])\n",
    "        except Exception as e:\n",
    "            fail_count += 1\n",
    "            if fail_count <= 5:\n",
    "                print(f'\\u26a0\\ufe0f {ticker} failed: {type(e).__name__}: {e}')\n",
    "            elif fail_count == 6:\n",
    "                print(f'\\u26a0\\ufe0f ... suppressing further error logs ...')\n",
    "            continue\n",
    "    if len(all_X) == 0:\n",
    "        print(f'\\u274c No valid data! {fail_count} tickers failed.')\n",
    "        return None, None, feature_names\n",
    "    print(f'\\u2705 Aggregated {len(all_X)} tickers ({fail_count} failed).')\n",
    "    return np.vstack(all_X), np.concatenate(all_y), feature_names\n",
    "\n",
    "def optimize_rf(X, y, n_trials=50):\n",
    "    print(f'\\U0001f50d Running Optuna HPO ({n_trials} trials)...')\n",
    "    def objective(trial):\n",
    "        params = {\n",
    "            'n_estimators': trial.suggest_int('n_estimators', 100, 500),\n",
    "            'max_depth': trial.suggest_int('max_depth', 5, 20),\n",
    "            'min_samples_leaf': trial.suggest_int('min_samples_leaf', 3, 20),\n",
    "            'max_features': trial.suggest_categorical('max_features', ['sqrt', 'log2']),\n",
    "        }\n",
    "        scores = walk_forward_cv(RandomForestClassifier, params, X, y, n_splits=4)\n",
    "        return np.mean(scores) if scores else 0.0\n",
    "    study = optuna.create_study(direction='maximize')\n",
    "    study.optimize(objective, n_trials=n_trials, timeout=600)\n",
    "    print(f'\\u2705 Optuna Best Val Acc: {study.best_value:.4f}')\n",
    "    print(f'\\u2705 Best Params: {study.best_params}')\n",
    "    return study.best_params, study.best_value\n",
]

for cell in data['cells']:
    if cell['cell_type'] == 'code':
        src = "".join(cell['source'])
        if "def build_panel_data" in src:
            cell['source'] = section3
            break

with open(f, 'w', encoding='utf-8') as file:
    json.dump(data, file, indent=1)
print("00A SECTION 3 FULLY REWRITTEN WITH DIAGNOSTICS!")
