import json

f = 'notebooks/00a_model_retraining_rf.ipynb'
with open(f, 'r', encoding='utf-8') as file:
    data = json.load(file)

section3 = [
    "# \U0001f9e0 SECTION 3: CORE LOGIC (Institutional Alpha Pipeline)\n",
    "from sklearn.ensemble import RandomForestClassifier\n",
    "from sklearn.model_selection import train_test_split\n",
    "import numpy as np\n",
    "import ta, optuna, warnings\n",
    "optuna.logging.set_verbosity(optuna.logging.WARNING)\n",
    "warnings.filterwarnings('ignore', category=FutureWarning)\n",
    "\n",
    "def frac_diff(series, d=0.4, window=100):\n",
    "    \"\"\"Fixed-width fractional differentiation (Lopez de Prado).\"\"\"\n",
    "    w = [1.0]\n",
    "    for k in range(1, window):\n",
    "        w.append(-w[-1] * (d - k + 1) / k)\n",
    "    w = np.array(w[::-1])\n",
    "    result = np.full(len(series), np.nan)\n",
    "    for t in range(window - 1, len(series)):\n",
    "        result[t] = np.dot(w, series[t - window + 1:t + 1])\n",
    "    return result\n",
    "\n",
    "def triple_barrier_label(close_arr, t_horizon=5, sl_pct=0.02, tp_pct=0.03):\n",
    "    labels = np.zeros(len(close_arr))\n",
    "    for i in range(len(close_arr) - t_horizon):\n",
    "        future = close_arr[i+1:i+1+t_horizon]\n",
    "        entry = close_arr[i]\n",
    "        if entry == 0:\n",
    "            continue\n",
    "        tp_hit = np.any(future >= entry * (1 + tp_pct))\n",
    "        sl_hit = np.any(future <= entry * (1 - sl_pct))\n",
    "        tp_idx = np.argmax(future >= entry * (1 + tp_pct)) if tp_hit else t_horizon\n",
    "        sl_idx = np.argmax(future <= entry * (1 - sl_pct)) if sl_hit else t_horizon\n",
    "        if tp_hit and (tp_idx <= sl_idx):\n",
    "            labels[i] = 1\n",
    "        elif sl_hit:\n",
    "            labels[i] = -1\n",
    "    return labels\n",
    "\n",
    "def walk_forward_cv(model_cls, model_params, X, y, n_splits=4):\n",
    "    chunk = len(X) // (n_splits + 1)\n",
    "    scores = []\n",
    "    for i in range(n_splits):\n",
    "        train_end = chunk * (i + 2)\n",
    "        test_end = min(train_end + chunk, len(X))\n",
    "        if test_end <= train_end:\n",
    "            continue\n",
    "        m = model_cls(**model_params, n_jobs=-1, random_state=42)\n",
    "        m.fit(X[:train_end], y[:train_end])\n",
    "        scores.append(m.score(X[train_end:test_end], y[train_end:test_end]))\n",
    "    return scores\n",
    "\n",
    "def build_panel_data(universe, period='5y'):\n",
    "    all_X, all_y = [], []\n",
    "    feature_names = ['Returns','RSI','MACD','BB_High','BB_Low','ATR','ADX','OBV_norm','day_of_week','week_of_month','frac_diff_close','vol_ratio']\n",
    "    n_total = len(universe)\n",
    "    print(f'\\U0001f4c9 Fetching {period} of data for {n_total} tickers...')\n",
    "    skip_empty = 0\n",
    "    skip_short = 0\n",
    "    skip_dropna = 0\n",
    "    fail_err = 0\n",
    "    ok_count = 0\n",
    "    for idx, ticker in enumerate(universe):\n",
    "        if idx % 50 == 0:\n",
    "            print(f'  ... processing {idx}/{n_total} ...')\n",
    "        try:\n",
    "            df = yf.download(ticker, period=period, progress=False, auto_adjust=True)\n",
    "            if df is None or len(df) == 0:\n",
    "                skip_empty += 1\n",
    "                continue\n",
    "            if len(df) < 150:\n",
    "                skip_short += 1\n",
    "                continue\n",
    "            close = df['Close'].squeeze()\n",
    "            high = df['High'].squeeze()\n",
    "            low = df['Low'].squeeze()\n",
    "            volume = df['Volume'].squeeze()\n",
    "            if hasattr(close, 'ndim') and close.ndim > 1:\n",
    "                close = close.iloc[:, 0]\n",
    "            if hasattr(high, 'ndim') and high.ndim > 1:\n",
    "                high = high.iloc[:, 0]\n",
    "            if hasattr(low, 'ndim') and low.ndim > 1:\n",
    "                low = low.iloc[:, 0]\n",
    "            if hasattr(volume, 'ndim') and volume.ndim > 1:\n",
    "                volume = volume.iloc[:, 0]\n",
    "            feat = pd.DataFrame(index=df.index)\n",
    "            feat['Returns'] = close.pct_change()\n",
    "            feat['RSI'] = ta.momentum.RSIIndicator(close=close, window=14).rsi()\n",
    "            macd_ind = ta.trend.MACD(close=close)\n",
    "            feat['MACD'] = macd_ind.macd_diff()\n",
    "            boll = ta.volatility.BollingerBands(close=close, window=20, window_dev=2)\n",
    "            feat['BB_High'] = boll.bollinger_hband_indicator()\n",
    "            feat['BB_Low'] = boll.bollinger_lband_indicator()\n",
    "            feat['ATR'] = ta.volatility.AverageTrueRange(high=high, low=low, close=close, window=14).average_true_range()\n",
    "            feat['ADX'] = ta.trend.ADXIndicator(high=high, low=low, close=close, window=14).adx()\n",
    "            obv = ta.volume.OnBalanceVolumeIndicator(close=close, volume=volume).on_balance_volume()\n",
    "            feat['OBV_norm'] = (obv - obv.rolling(20).mean()) / (obv.rolling(20).std() + 1e-7)\n",
    "            feat['day_of_week'] = df.index.dayofweek\n",
    "            feat['week_of_month'] = (df.index.day - 1) // 7\n",
    "            feat['frac_diff_close'] = frac_diff(close.values.flatten(), d=0.4, window=100)\n",
    "            vol_ma = volume.rolling(20).mean()\n",
    "            feat['vol_ratio'] = volume / (vol_ma + 1e-7)\n",
    "            feat = feat.dropna()\n",
    "            if len(feat) < 50:\n",
    "                skip_dropna += 1\n",
    "                continue\n",
    "            close_arr = close.reindex(feat.index).values.flatten()\n",
    "            y = triple_barrier_label(close_arr, t_horizon=5, sl_pct=0.02, tp_pct=0.03)\n",
    "            valid = min(len(feat), len(y))\n",
    "            X = feat[feature_names].values[:valid]\n",
    "            y = y[:valid]\n",
    "            mask = ~np.isnan(X).any(axis=1)\n",
    "            if mask.sum() > 0:\n",
    "                all_X.append(X[mask])\n",
    "                all_y.append(y[mask])\n",
    "                ok_count += 1\n",
    "        except Exception as e:\n",
    "            fail_err += 1\n",
    "            if fail_err <= 5:\n",
    "                print(f'\\u26a0\\ufe0f {ticker}: {type(e).__name__}: {e}')\n",
    "            continue\n",
    "    print(f'\\U0001f4ca Pipeline: OK={ok_count} | Empty={skip_empty} | Short={skip_short} | Dropna={skip_dropna} | Error={fail_err}')\n",
    "    if len(all_X) == 0:\n",
    "        print(f'\\u274c No valid data from {n_total} tickers!')\n",
    "        return None, None, feature_names\n",
    "    Xr = np.vstack(all_X)\n",
    "    yr = np.concatenate(all_y)\n",
    "    print(f'\\u2705 Aggregated {ok_count}/{n_total} tickers | {len(yr)} samples.')\n",
    "    return Xr, yr, feature_names\n",
    "\n",
    "def optimize_rf(X, y, n_trials=50):\n",
    "    print(f'\\U0001f50d Running Optuna HPO ({n_trials} trials)...')\n",
    "    def objective(trial):\n",
    "        params = {\n",
    "            'n_estimators': trial.suggest_int('n_estimators', 100, 500),\n",
    "            'max_depth': trial.suggest_int('max_depth', 5, 20),\n",
    "            'min_samples_leaf': trial.suggest_int('min_samples_leaf', 3, 20),\n",
    "            'max_features': trial.suggest_categorical('max_features', ['sqrt', 'log2']),\n",
    "        }\n",
    "        scores = walk_forward_cv(RandomForestClassifier, params, X, y, n_splits=4)\n",
    "        return np.mean(scores) if scores else 0.0\n",
    "    study = optuna.create_study(direction='maximize')\n",
    "    study.optimize(objective, n_trials=n_trials, timeout=600)\n",
    "    print(f'\\u2705 Optuna Best Val Acc: {study.best_value:.4f}')\n",
    "    print(f'\\u2705 Best Params: {study.best_params}')\n",
    "    return study.best_params, study.best_value\n",
]

for cell in data['cells']:
    if cell['cell_type'] == 'code':
        src = "".join(cell['source'])
        if "def build_panel_data" in src:
            cell['source'] = section3
            break

with open(f, 'w', encoding='utf-8') as file:
    json.dump(data, file, indent=1)
print("00A FIXED: frac_diff window=100, separate feat DataFrame, yfinance warnings suppressed!")
