import json

f = 'notebooks/02_signal_inference.ipynb'
with open(f, 'r', encoding='utf-8') as file:
    data = json.load(file)

# ═══════════════════════════════════════════════
# SECTION 3: Predictors updated for Phase 18
# ═══════════════════════════════════════════════
section3 = [
    "# \U0001f9e0 SECTION 3: CORE LOGIC (Institutional Predictors & Meta-Label Gate)\n",
    "import ta\n",
    "\n",
    "def frac_diff(series, d=0.4, thres=1e-5):\n",
    "    weights = [1.0]\n",
    "    for k in range(1, len(series)):\n",
    "        w = -weights[-1] * (d - k + 1) / k\n",
    "        if abs(w) < thres:\n",
    "            break\n",
    "        weights.append(w)\n",
    "    weights = np.array(weights[::-1])\n",
    "    result = np.full(len(series), np.nan)\n",
    "    for t in range(len(weights) - 1, len(series)):\n",
    "        result[t] = np.dot(weights, series[t - len(weights) + 1:t + 1])\n",
    "    return result\n",
    "\n",
    "class MLPredictor:\n",
    "    def __init__(self, model_dir):\n",
    "        path = os.path.join(model_dir, 'glu_brain_v1.joblib')\n",
    "        brain = joblib.load(path)\n",
    "        self.model = brain.get('model')\n",
    "        self.features = brain.get('features', [])\n",
    "        self.train_acc = brain.get('train_accuracy', 0)\n",
    "        self.val_acc = brain.get('val_accuracy', 0)\n",
    "        print(f'\u2705 RF Model loaded: {len(self.features)} features | Val Acc: {self.val_acc:.2%}')\n",
    "\n",
    "    def build_features(self, df):\n",
    "        close = df['Close'].squeeze()\n",
    "        high = df['High'].squeeze()\n",
    "        low = df['Low'].squeeze()\n",
    "        volume = df['Volume'].squeeze()\n",
    "        feat = pd.DataFrame(index=df.index)\n",
    "        feat['Returns'] = close.pct_change()\n",
    "        feat['RSI'] = ta.momentum.RSIIndicator(close=close, window=14).rsi()\n",
    "        macd = ta.trend.MACD(close=close)\n",
    "        feat['MACD'] = macd.macd_diff()\n",
    "        boll = ta.volatility.BollingerBands(close=close, window=20, window_dev=2)\n",
    "        feat['BB_High'] = boll.bollinger_hband_indicator()\n",
    "        feat['BB_Low'] = boll.bollinger_lband_indicator()\n",
    "        feat['ATR'] = ta.volatility.AverageTrueRange(high=high, low=low, close=close, window=14).average_true_range()\n",
    "        feat['ADX'] = ta.trend.ADXIndicator(high=high, low=low, close=close, window=14).adx()\n",
    "        obv = ta.volume.OnBalanceVolumeIndicator(close=close, volume=volume).on_balance_volume()\n",
    "        feat['OBV_norm'] = (obv - obv.rolling(20).mean()) / (obv.rolling(20).std() + 1e-7)\n",
    "        feat['day_of_week'] = df.index.dayofweek\n",
    "        feat['week_of_month'] = (df.index.day - 1) // 7\n",
    "        fd = frac_diff(close.values, d=0.4)\n",
    "        feat['frac_diff_close'] = fd\n",
    "        vol_ma = volume.rolling(20).mean()\n",
    "        feat['vol_ratio'] = volume / (vol_ma + 1e-7)\n",
    "        feat = feat.dropna()\n",
    "        return feat\n",
    "\n",
    "    def predict(self, df):\n",
    "        try:\n",
    "            feat = self.build_features(df)\n",
    "            if len(feat) == 0:\n",
    "                return 0, 0.5\n",
    "            row = feat[self.features].tail(1)\n",
    "            pred = self.model.predict(row)[0]\n",
    "            proba = self.model.predict_proba(row)[0]\n",
    "            confidence = max(proba)\n",
    "            return int(pred), float(confidence)\n",
    "        except Exception:\n",
    "            return 0, 0.5\n",
    "\n",
    "class CNNPredictor:\n",
    "    def __init__(self, model_dir):\n",
    "        self.interpreters = {}\n",
    "        for h in ['daily_t2']:\n",
    "            path = os.path.join(model_dir, f'cnn_{h}.tflite')\n",
    "            if os.path.exists(path):\n",
    "                self.interpreters[h] = tflite.Interpreter(model_path=path)\n",
    "                self.interpreters[h].allocate_tensors()\n",
    "                print(f'\u2705 CNN TFLite loaded: {h}')\n",
    "\n",
    "    def predict(self, df):\n",
    "        try:\n",
    "            interpreter = self.interpreters['daily_t2']\n",
    "            close = df['Close'].squeeze()\n",
    "            high = df['High'].squeeze()\n",
    "            low = df['Low'].squeeze()\n",
    "            volume = df['Volume'].squeeze()\n",
    "            atr = ta.volatility.AverageTrueRange(high=high, low=low, close=close, window=14).average_true_range()\n",
    "            raw = np.column_stack([df['Open'].squeeze().values, high.values, low.values, close.values, volume.values, atr.values])\n",
    "            valid_start = np.argmax(~np.isnan(raw).any(axis=1))\n",
    "            raw = raw[valid_start:]\n",
    "            seq = raw[-30:]\n",
    "            seq_min = seq.min(axis=0)\n",
    "            seq_max = seq.max(axis=0)\n",
    "            norm_seq = (seq - seq_min) / (seq_max - seq_min + 1e-7)\n",
    "            input_details = interpreter.get_input_details()\n",
    "            expected_shape = input_details[0]['shape']\n",
    "            n_features = expected_shape[-1]\n",
    "            input_data = np.expand_dims(norm_seq[:, :n_features].astype(np.float32), axis=0)\n",
    "            interpreter.set_tensor(input_details[0]['index'], input_data)\n",
    "            interpreter.invoke()\n",
    "            output = interpreter.get_tensor(interpreter.get_output_details()[0]['index'])[0]\n",
    "            return float(output[1]) if len(output) > 1 else float(output[0])\n",
    "        except Exception as e:\n",
    "            print(f'\u26a0\ufe0f CNN predict error: {e}')\n",
    "            return 0.5\n",
]

# ═══════════════════════════════════════════════
# SECTION 4: Meta-Label Gated Execution
# ═══════════════════════════════════════════════
section4 = [
    "# \U0001f680 SECTION 4: MAIN EXECUTION (Meta-Label Gated)\n",
    "META_CONFIDENCE_THRESHOLD = 0.60\n",
    "\n",
    "def run_inference():\n",
    "    secrets = KaggleInfra.load_secrets()\n",
    "    fb = FirebaseHandler(secrets)\n",
    "    \n",
    "    model_dir = '/kaggle/input/glustock-brains'\n",
    "    if not os.path.exists(model_dir):\n",
    "        print('\u274c Models missing! Please add glustock-brains dataset.')\n",
    "        return\n",
    "    \n",
    "    candidates = fb.get_and_clear_queue('research')\n",
    "    if not candidates:\n",
    "        print('\U0001f4ed Queue empty.')\n",
    "        return\n",
    "    \n",
    "    rf = MLPredictor(model_dir)\n",
    "    cnn = CNNPredictor(model_dir)\n",
    "    signals = {}\n",
    "    skipped = 0\n",
    "    \n",
    "    for ticker_list in candidates:\n",
    "        for ticker in ticker_list:\n",
    "            print(f'\U0001f52c Analyzing {ticker}...')\n",
    "            df = yf.download(ticker, period='90d', interval='1d', progress=False)\n",
    "            if len(df) < 50:\n",
    "                continue\n",
    "            \n",
    "            # 1. RF Base Prediction (3-class: -1, 0, +1)\n",
    "            rf_signal, rf_conf = rf.predict(df)\n",
    "            \n",
    "            # 2. CNN Meta-Label Confidence\n",
    "            cnn_conf = cnn.predict(df)\n",
    "            \n",
    "            # 3. Meta-Label Gate: Only execute if RF says BUY (+1) AND CNN confidence is high\n",
    "            if rf_signal == 1 and cnn_conf >= META_CONFIDENCE_THRESHOLD:\n",
    "                signals[ticker] = {\n",
    "                    'conviction': float(cnn_conf),\n",
    "                    'rf_signal': int(rf_signal),\n",
    "                    'rf_confidence': float(rf_conf),\n",
    "                    'meta_confidence': float(cnn_conf),\n",
    "                    'price': float(df['Close'].iloc[-1]),\n",
    "                    'timestamp': datetime.now().isoformat()\n",
    "                }\n",
    "                print(f'\U0001f525 {ticker} APPROVED (RF: +1 @ {rf_conf:.0%} | Meta: {cnn_conf:.0%})')\n",
    "            else:\n",
    "                skipped += 1\n",
    "                reason = 'RF=HOLD/SELL' if rf_signal != 1 else f'Meta={cnn_conf:.0%}<{META_CONFIDENCE_THRESHOLD:.0%}'\n",
    "                print(f'\u26d4 {ticker} BLOCKED ({reason})')\n",
    "    \n",
    "    if signals:\n",
    "        fb.push_task('signals', signals)\n",
    "        log_lines = [\n",
    "            f'Meta-Label Inference Complete.',\n",
    "            f'\u2705 Approved: {len(signals)} signals',\n",
    "            f'\u26d4 Blocked: {skipped} (False Positive filter)',\n",
    "            f'\U0001f3af Gate Threshold: {META_CONFIDENCE_THRESHOLD:.0%}',\n",
    "        ]\n",
    "        for t, s in signals.items():\n",
    "            log_lines.append(f'  {t}: RF={s[\"rf_confidence\"]:.0%} | Meta={s[\"meta_confidence\"]:.0%}')\n",
    "        fb.log_event('INFERENCE', chr(10).join(log_lines))\n",
    "        for line in log_lines:\n",
    "            print(line)\n",
    "    else:\n",
    "        fb.log_event('INFERENCE', f'No signals passed Meta-Label gate. {skipped} candidates blocked.')\n",
    "        print(f'\U0001f6e1\ufe0f All {skipped} candidates blocked by Meta-Label gate.')\n",
    "\n",
    "run_inference()\n",
]

# ── Also update pip install cell ──
for cell in data['cells']:
    if cell['cell_type'] == 'code':
        src = "".join(cell['source'])
        if '!pip install' in src:
            if 'ta' not in src:
                new_src = src.rstrip() + ' ta'
                cell['source'] = [new_src]

# ── Inject into correct cells ──
for cell in data['cells']:
    if cell['cell_type'] == 'code':
        src = "".join(cell['source'])
        if "class MLPredictor" in src:
            cell['source'] = section3
        elif "def run_inference" in src:
            cell['source'] = section4

with open(f, 'w', encoding='utf-8') as file:
    json.dump(data, file, indent=1)
print("02 SIGNAL INFERENCE PATCHED WITH META-LABEL GATE!")
